title: Your Mom
date: 2018-07-03

author: Your Other Mom
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Ur Mom lol

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
